version: "3"

services:
    db: 
        image: postgres:alpine
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: senha
        ports:
            - "5432:5432"
    node:
        image: node
        container_name: node-container
        ports:
            - "3000:3000"
        depends_on:
            - db