const {v4} = require("uuid");

exports.seed = function(knex) {
  
  return knex('crews').del()
    .then(function () {
      
      return knex('crews').insert([
		    {id: v4(), name: "WIE", about: "É a equipe responsável por promover projetos, ações e iniciativas que fomentem e/ou garantam que mulheres e meninas possam ter acesso ao ambiente acadêmico e profissional, especialmente, mas não restrito, à ciência, tecnologia, engenharia, matemática e demais áreas exatas. Atualmente é dividida em 4 subequipes: Projetos, Eventos, Mídias e Produtos. Dentro do Ramo, a equipe também é responsável por avaliar o clima de conforto das mulheres em relação ao ambiente, e promover a conscientização de membros homens através de workshops sobre como se portar para tornar o ambiente agradável para todos.", imageURL: "WIE_crew_avatar.svg"},
        {id: v4(), name: "Gestão", about: "É equipe responsável por lidar com toda a gestão organizacional do Ramo Estudantil: criação de planejamento estratégico das equipes, descrição de cargos, estrutura organizacional, análise dos processos e documentações existentes, gestão de conhecimento, captação de novos membros e retenção dos membros atuais. Possui três diretorias: Gestão de Pessoas, Gestão de Projetos e Gestão Financeira. Além de possuir uma presidência e vice-presidência que representa nosso Ramo Estudantil para a comunidade externa e os coordenadores de cada equipe que respondem pela necessidade particular que cada equipe possui.", imageURL: "Gestão_crew_avatar.svg"}, 
        {id: v4(), name: "Marketing", about: "É a equipe responsável por gerenciar a imagem e comunicação externa de todas as equipes do Ramo Estudantil WolfBotz, WolfPower, WolfByte, RocketWolf, SocialWolf e WIE. Para isso a equipe é dividida em 4 frentes: Mídias Sociais, Gestão de Eventos, Gestão de Parcerias e Elaboração de Produtos.", imageURL: "Marketing_crew_avatar.svg"},
        {id: v4(), name: "RocketWolf", about: "Essa é a equipe que desenvolve pesquisas e projetos no segmento aeroespacial, com enfoque na criação de foguetes experimentais para participação em festivais, competições, simpósios, entre outros eventos, com o propósito de difundir a cultura do foguetemodelismo. A equipe constrói esses foguetes desde o projeto até a execução, tendo em vista a divisão em subsistemas de: Aerodinâmica, Mecânica de Vôo, Eletrônica, Estruturas, Propulsão e Recuperação. Desde a criação da equipe em 2016, foram construídos aproximadamente 10 foguetes. O que demonstra o grande conhecimento que a equipe possui nessa área da ciência, pela vasta experiência.", imageURL: "RocketWolf_crew_avatar.svg"},
        {id: v4(), name: "SocialWolf", about:"A SocialWolf é a nossa equipe de impacto e responsabilidade social. Portanto os projetos possuem sempre o objetivo de impactar uma comunidade em vulnerabilidade. Atualmente a equipe é dividida em duas subequipes: IEEE na Escola, que tem como objetivo levar tecnologia e inovação a centros educacionais e Projetos Técnicos Sociais, que busca encontrar uma solução técnica para algum problema que uma comunidade possa estar sofrendo.", imageURL: "SocialWolf_crew_avatar.svg"},
        {id: v4(), name: "WolfBotz", about: "É nossa equipe de robótica que tem como principal foco, o desenvolvimento dos membros nas áreas de: programação, mecânica e eletrônica. Já foram feitas dezenas de robôs funcionais e a equipe possui forte presença nas competições nacionais como a IronCup, RSM Challenge e Hacktudo.", imageURL: "WolfBotz_crew_avatar.svg"},
        {id: v4(), name: "WolfByte", about: "É a nossa equipe de programação que desenvolve habilidades na área de WEB, APP, Jogos, UI/UX Design, Arte e Som, produção de Inteligências artificiais e construção de hardwares modernos com foco em eletrônica e programação. A equipe possui 4 subequipes fixas onde realizam projetos focados em: Inteligência Artificial (IA), WEB/APP, Games e Hardware. Seu trabalho consiste na criação de projetos inovadores e participação em hackathons.", imageURL: "WolfByte_crew_avatar.svg"},
        {id: v4(), name: "WolfPower", about: "É a equipe de potência e energia do Ramo estudantil IEEE CEFET/RJ que possui como principais objetivos, estudar e desenvolver projetos e pesquisas que tratam temáticas como a produção, o uso e a eficiência de energias limpas e renováveis, além de tecnologias oriundas ou beneficiadas por essas vertentes, buscando soluções para o uso desenfreado de fontes de energias não renováveis e poluentes. Além disso, a equipe também trabalha promovendo eventos que tragam a conscientização para a comunidade acadêmica.", imageURL: "WolfPower_crew_avatar.svg"}
      ]);
    });
};
